### PR TITLE
CAR-672   upgrade to protobuf 3

### PR DESCRIPTION
**Pull request by artasano**

### CODE REVIEW

**Comment by artasano** [comment]
@jim-wong Recreated PR

**Comment by jim-wong** [comment]
@artasano It looks like this merge pulls in one protobuf change beyond the 3.3.1 release: https://github.com/google/protobuf/pull/3085

Rather than recreate the whole thing again, do you want to take a quick look at that PR to make sure we're OK with it? It looked fine to me, but you've spent more time with this code than I have.

**Comment by artasano** [comment]
@jim, they have branch 3.3.x and I don't know how to specify 3.3.1. How did you know it is beyond 3.3.1?

**Comment by artasano** [comment]
#3085 has no code change (just suppressing unused-arg compiler warnings)

**Comment by jim-wong** [comment]
@artasano We should be able to bring in a version of a code based on a tag instead of a branch. The tag in this case is `v3.3.1`.

You can tell that there are changes on 3.3.x after 3.3.1 by looking at the commit history.

**Pull request merged**
